plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - recruit2021.md
theme: jekyll-theme-minimal
markdown: kramdown
title: MI-TW ((Medical Informatics) 2021 
logo: https://mitw.dicom.org.tw/img/logo.png
