plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - recruit2021.md
theme: jekyll-theme-minimal
markdown: kramdown
title: 2021 台灣醫學資訊聯測(MI-TW) 
logo: https://mitw.dicom.org.tw/img/logo.png
